# ============================================================
# TradeMatrix.ai – MR-06: Yesterday Range Reversion
# Purpose: Mean reversion from yesterday's extremes to pivot
# Confidence Target: 0.83+ (PRIORITY SETUP)
# ============================================================

strategy:
  id: "MR-06"
  name: "Yesterday Range Reversion"
  description: "Touch yesterday's high/low ±10 points, mean revert to Pivot PP"
  priority: 1  # HIGH PRIORITY - Overrides MR-02
  category: "mean_reversion"
  timeframe: "5m"

entry_conditions:
  # Primary signal: Touch yesterday's extreme
  - type: "level_touch"
    levels: ["yesterday_high", "yesterday_low"]
    tolerance_points: 10
    description: "Price touches yesterday's high or low within 10 points"

  # Rejection confirmation
  - type: "rejection_candle"
    patterns: ["pin_bar", "engulfing", "shooting_star", "hammer"]
    min_wick_ratio: 0.5
    description: "Candle shows clear rejection from the level"

  # Distance from Pivot PP
  - type: "pivot_distance"
    min_distance_points: 40
    reference: "pivot_pp"
    description: "Must be at least 40 points from pivot to have profit potential"

  # Market structure
  - type: "range_bound_market"
    method: "atr_analysis"
    max_atr_expansion: 1.5
    description: "Market should be in consolidation/ranging mode"

  # Volume (less critical for mean reversion)
  - type: "volume_confirmation"
    min_volume_ratio: 0.8
    lookback_periods: 20
    required: false
    description: "Average or above average volume preferred"

exit_conditions:
  # Take Profit: Pivot PP
  - type: "take_profit"
    target: "pivot_pp"
    description: "Primary target: Central pivot point"
    required: true

  # Stop Loss: Beyond extreme
  - type: "stop_loss"
    method: "beyond_extreme"
    buffer_points: 25
    description: "25 points beyond yesterday's high/low"
    max_risk_points: 50

  # Partial profit
  - type: "partial_profit"
    percent: 50
    trigger_rrr: 1.0
    description: "Take 50% profit at 1:1, let rest run to PP"

  # Breakeven
  - type: "move_to_breakeven"
    trigger_rrr: 0.5
    lock_in_points: 5

risk_management:
  max_risk_percent: 1.0
  position_type: "CFD"
  breakeven_at_rrr: 0.5
  max_concurrent_positions: 1
  priority_override: true  # Can override other setups

validation_metrics:
  ema_alignment:
    weight: 0.25
    required_score: 0.75

  pivot_confluence:
    weight: 0.20
    required_score: 0.85
    note: "Critical - pivot PP is the target"

  volume_confirmation:
    weight: 0.20
    required_score: 0.70

  candle_structure:
    weight: 0.20
    required_score: 0.85
    note: "Rejection candle must be clear"

  context_flow:
    weight: 0.15
    required_score: 0.75

  min_confidence_score: 0.83

market_conditions:
  preferred_session: ["EU_session", "US_session"]
  best_time_window:
    start: "09:00"
    end: "17:00"
    timezone: "CET"
  preferred_volatility: "low_to_medium"
  ideal_market_state: "range_bound"
  avoid_during: ["strong_trends", "major_news"]

priority_rules:
  overrides: ["MR-02"]  # Overrides Pivot Rebound setups
  description: "Yesterday's range is stronger mean reversion level than intraday pivots"

range_analysis:
  # Calculate range characteristics
  - type: "range_width"
    min_width_points: 80
    description: "Yesterday's range should be at least 80 points for meaningful reversion"

  - type: "current_position"
    check: "within_range"
    description: "Price should be near extremes, not in middle of range"

  - type: "range_age"
    max_age_days: 1
    description: "Only use previous day's range, not older"

confluence_factors:
  # Additional factors that boost confidence
  - type: "round_number"
    proximity_points: 20
    confidence_boost: 0.03

  - type: "fibonacci_level"
    levels: [0.618, 0.5, 0.382]
    tolerance: 0.02
    confidence_boost: 0.04

  - type: "previous_pivot"
    matches: ["yesterday_pp", "weekly_pp"]
    confidence_boost: 0.05

  - type: "multiple_rejections"
    min_rejections: 2
    lookback_days: 5
    confidence_boost: 0.06

scaling_strategy:
  # Optional: Scale into position
  initial_entry: 0.6  # 60% at first rejection
  add_on:
    condition: "second_rejection"
    size: 0.4  # Add 40% if price retests and rejects again
    max_wait_minutes: 30

notes: |
  - **PRIORITY SETUP** - High confidence mean reversion
  - Yesterday's high/low are significant psychological levels
  - Pivot PP acts as magnet in ranging markets
  - Look for clear rejection candles (long wicks)
  - ±10 point tolerance allows for stop hunts
  - Stop 25 points beyond extreme captures invalidation
  - Target (PP) should give at least 2:1 RRR
  - Best in ranging/consolidating markets
  - Avoid during trending days or news events
  - Can scale in on second rejection for higher confidence

examples:
  - scenario: "NASDAQ touches yesterday's high at 14:30, shooting star"
    yesterday_high: "16550"
    touch_price: "16545"
    pivot_pp: "16480"
    entry: "16540"
    stop_loss: "16575"
    take_profit: "16480"
    risk_reward: "1.7"
    confidence: "0.83"
    notes: "Clear rejection, range-bound market, 70 points to PP"
