# ============================================================
# TradeMatrix.ai – MR-01: EMA Cross Reversal
# Purpose: Trend reversal detection via EMA crossover
# Confidence Target: 0.75+
# ============================================================

strategy:
  id: "MR-01"
  name: "EMA Cross Reversal"
  description: "EMA20 crosses above EMA50, price above Ichimoku Cloud"
  priority: 2
  category: "trend_reversal"
  timeframe: "5m"

entry_conditions:
  # Primary signal: EMA crossover
  - type: "ema_cross"
    ema_fast: 20
    ema_slow: 50
    direction: "bullish"  # fast crosses above slow

  # Confirmation: Price position
  - type: "price_above_cloud"
    ichimoku:
      tenkan: 9
      kijun: 26
      senkou_span_b: 52

  # Additional filter: Trend strength
  - type: "price_above_ema"
    ema_period: 200
    description: "Price must be above EMA200 for valid long setup"

  # Volume confirmation
  - type: "volume_confirmation"
    min_volume_ratio: 1.0  # At least average volume
    lookback_periods: 20

exit_conditions:
  # Take Profit
  - type: "take_profit"
    risk_reward_ratio: 2.0
    description: "Exit at 2:1 RRR"

  # Stop Loss
  - type: "stop_loss"
    method: "swing_low"
    buffer_points: 15
    description: "Below recent swing low with 15-point buffer"

  # Trailing Stop (optional)
  - type: "trailing_stop"
    activation_rrr: 1.0
    trail_distance_points: 20

  # Time-based exit
  - type: "time_exit"
    max_hold_minutes: 240
    description: "Close position after 4 hours if not triggered"

risk_management:
  max_risk_percent: 1.0
  position_type: "CFD"
  breakeven_at_rrr: 0.5
  max_daily_trades: 3

validation_metrics:
  ema_alignment:
    weight: 0.25
    required_score: 0.70

  pivot_confluence:
    weight: 0.20
    required_score: 0.60

  volume_confirmation:
    weight: 0.20
    required_score: 0.70

  candle_structure:
    weight: 0.20
    required_score: 0.65

  context_flow:
    weight: 0.15
    required_score: 0.60

  min_confidence_score: 0.75

market_conditions:
  preferred_session: ["EU_session", "US_session"]
  avoid_sessions: ["low_volume_asian"]
  preferred_volatility: "medium_to_high"

notes: |
  - Wait for full candle close to confirm EMA cross
  - Best results during trending markets
  - Avoid during major news events
  - Works well on DAX, NASDAQ, Dow Jones

examples:
  - scenario: "DAX crosses EMA20 above EMA50 at 08:30 CET"
    entry: "15800"
    stop_loss: "15770"
    take_profit: "15860"
    risk_reward: "2.0"
