-- Migration 005: Signals Table for SignalBot Agent
-- Purpose: Store entry/exit signals generated by SignalBot
-- Date: 2025-10-29

-- Create signals table
CREATE TABLE IF NOT EXISTS signals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol_id UUID REFERENCES market_symbols(id) ON DELETE CASCADE,
  setup_id UUID REFERENCES setups(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Signal type
  signal_type TEXT NOT NULL CHECK(signal_type IN ('entry', 'exit', 'update')),

  -- Trade details
  side TEXT CHECK(side IN ('long', 'short')),
  entry_price NUMERIC,
  stop_loss NUMERIC,
  take_profit NUMERIC,
  position_size NUMERIC,

  -- Validation results
  confidence NUMERIC CHECK(confidence >= 0 AND confidence <= 1),
  validation_breakdown JSONB,

  -- Market context
  context JSONB,

  -- Status tracking
  status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'active', 'executed', 'cancelled', 'expired')),
  executed_at TIMESTAMPTZ,
  expired_at TIMESTAMPTZ,

  -- Full signal payload
  payload JSONB
);

-- Create indexes
CREATE INDEX idx_signals_user_id ON signals(user_id);
CREATE INDEX idx_signals_symbol_id ON signals(symbol_id);
CREATE INDEX idx_signals_setup_id ON signals(setup_id);
CREATE INDEX idx_signals_status ON signals(status);
CREATE INDEX idx_signals_created_at ON signals(created_at DESC);
CREATE INDEX idx_signals_signal_type ON signals(signal_type);

-- Add updated_at trigger
CREATE TRIGGER signals_updated_at
  BEFORE UPDATE ON signals
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- RLS Policies
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;

-- Users can read their own signals
CREATE POLICY "Users can read own signals"
  ON signals FOR SELECT
  USING (auth.uid() = user_id);

-- Service role can manage all signals
CREATE POLICY "Service role can manage all signals"
  ON signals FOR ALL
  USING (auth.role() = 'service_role');

-- Comment
COMMENT ON TABLE signals IS 'Entry/exit signals generated by SignalBot agent';
