-- ================================================
-- Migration 007: Reports Table
-- ================================================
-- Purpose: Add reports table for JournalBot automated report metadata
-- Created: 2025-10-29
-- Author: TradeMatrix.ai Development Team
-- ================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ================================================
-- TABLE: reports
-- ================================================
-- Stores metadata for automated trading reports (PDF/DOCX)
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Report metadata
  report_type TEXT NOT NULL CHECK(report_type IN ('daily', 'weekly', 'monthly')),
  report_date DATE NOT NULL,

  -- File URLs (Supabase Storage)
  file_url_pdf TEXT,
  file_url_docx TEXT,

  -- Performance metrics (JSON)
  metrics JSONB DEFAULT '{}',

  -- Constraints
  CONSTRAINT reports_user_date_type_unique UNIQUE(user_id, report_date, report_type)
);

-- Indexes for fast queries
CREATE INDEX idx_reports_user_id ON reports(user_id);
CREATE INDEX idx_reports_date ON reports(report_date DESC);
CREATE INDEX idx_reports_type ON reports(report_type);
CREATE INDEX idx_reports_created_at ON reports(created_at DESC);

-- ================================================
-- TRIGGER: Auto-update timestamps
-- ================================================

DROP TRIGGER IF EXISTS update_reports_updated_at ON reports;
CREATE TRIGGER update_reports_updated_at
  BEFORE UPDATE ON reports
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ================================================
-- RLS POLICIES
-- ================================================

-- Enable RLS
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own reports
CREATE POLICY "Users can view own reports"
  ON reports
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Service role can insert reports (JournalBot agent)
CREATE POLICY "Service role can insert reports"
  ON reports
  FOR INSERT
  WITH CHECK (true);  -- Service role bypasses RLS

-- Policy: Service role can update reports
CREATE POLICY "Service role can update reports"
  ON reports
  FOR UPDATE
  USING (true);  -- Service role bypasses RLS

-- Policy: Users can delete their own reports
CREATE POLICY "Users can delete own reports"
  ON reports
  FOR DELETE
  USING (auth.uid() = user_id);

-- ================================================
-- COMMENTS
-- ================================================

COMMENT ON TABLE reports IS 'Automated trading report metadata (generated by JournalBot)';
COMMENT ON COLUMN reports.report_type IS 'Report frequency: daily, weekly, or monthly';
COMMENT ON COLUMN reports.report_date IS 'Date for which report was generated';
COMMENT ON COLUMN reports.file_url_pdf IS 'Public URL to PDF report in Supabase Storage';
COMMENT ON COLUMN reports.file_url_docx IS 'Public URL to DOCX report in Supabase Storage';
COMMENT ON COLUMN reports.metrics IS 'Performance metrics JSON (total_trades, win_rate, pnl, etc.)';

-- ================================================
-- END OF MIGRATION 007
-- ================================================
