/**
 * API Route: POST /api/reports/generate
 *
 * Triggers manual report generation by calling the Celery worker
 */

import { createServerClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

export async function POST(request: Request) {
  try {
    // Verify user is authenticated
    const supabase = await createServerClient()
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get report type from request body
    const body = await request.json().catch(() => ({}))
    const reportType = body.report_type || 'daily'

    // Validate report type
    const validTypes = ['daily', 'weekly', 'monthly', 'trade_analysis', 'risk_assessment']
    if (!validTypes.includes(reportType)) {
      return NextResponse.json(
        { error: `Invalid report type. Must be one of: ${validTypes.join(', ')}` },
        { status: 400 }
      )
    }

    // For now, create a placeholder report with 'processing' status
    // In production, this would trigger the Celery task on Hetzner
    // via HTTP request to Celery Flower API or direct Redis queue
    const { data: report, error: insertError } = await (supabase as any)
      .from('reports')
      .insert({
        user_id: user.id,
        title: `${reportType.charAt(0).toUpperCase() + reportType.slice(1).replace('_', ' ')} Report - ${new Date().toLocaleDateString()}`,
        content: 'Report is being generated...',
        report_type: reportType,
        ai_summary: null,
        ai_insights: [],
        status: 'processing',
        metrics: {},
        metadata: {
          triggered_by: 'manual',
          triggered_at: new Date().toISOString(),
        },
      })
      .select()
      .single()

    if (insertError) {
      console.error('Error creating report:', insertError)
      return NextResponse.json(
        { error: 'Failed to create report', details: insertError.message },
        { status: 500 }
      )
    }

    // TODO: Trigger Celery task on Hetzner
    // Example: POST to http://135.181.195.241:5555/api/task/async-apply/run_journal_bot
    // For now, the report will stay in 'processing' status
    // The scheduled Celery task will pick it up at 21:00

    return NextResponse.json({
      message: 'Report generation started',
      report_id: report.id,
      status: 'processing',
      note: 'Report will be generated by the scheduled task at 21:00 MEZ or you can trigger it manually via Celery',
    })
  } catch (error: any) {
    console.error('Unexpected error in /api/reports/generate:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    )
  }
}
